### ISSUE TITLE
urn:cts:greekLit:tlg5026.e3.hmt:17.E3_224r_1

### ISSUE THREAD

**Issue by LisaSeldenthuis** [homermultitext/scholia-english#23] opened 2019-07-05 15:51 UTC
Lemma (leave blank if no lemma):

Comment: It is a good thing that Menelaos is the first to notice that Patroclus has fallen, for he says "he lies here because of my honor"; and because they have similar characters, for both are gentle; and Menelaos is gentle not only to those under his command, but also to his enemies; or because he is seen as zealous with respect to everyone; he who, even when Odysseus was in trouble, came and brought Ajax. And he got out of bed before his brother; or because he made Achilles a more eager ally for himself; alternatively the others are wounded with the exception of Ajax, who should not yield to Hector.

Extra comment: translated by Victoria Ydens and Lisa Seldenthuis
This is the first scholion of book 17, scholion ιβ

**Comment by caseydue** [comment] 2019-07-25 16:22
This is a duplicate of the previous issue.

**Closed as completed by caseydue** 2019-07-25 16:22 UTC
